# Generated by Django 5.2.8 on 2025-11-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('fichier_video', models.FileField(upload_to='videos/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
